- config.php
- rallye-digital/index.php
- wanderung2/index.php
Update events and times. Registration & updated registration text will be added with a separate PR.
> Update events to WS20/21

- config.php
- rallye/index.php
- wanderung/index.php
This PR will add the "Stadtrallye" and "Wanderung"
> add two events

- README.md
- config.php
- css/index.css
- css/style.css
- index.php
- rallye/index.php
- wanderung/index.php
Changed some css
Events that are not 100% gonna happen will be displayed washed out and their registration is uncommented.
I hope that this addressed the issues @luoe had with the previous version.
> Resolve misunderstandable events

- config.php
- wanderung/index.php
Alle Veranstaltungen, die bereits stattgefunden haben, wurden auskommentiert. Sieht bissle leer aus.
> Wanderung eingetragen

- config.php
- sommerfest/index.php
Changed the text of the Sommerfest event because we don't offer pizza.
Also commented out events from last year and the beginning of 2021.
> Corrected Sommerfest description and removal of old events.

- config.php
Added functionality to change the default time that registration closes and changed this time for Sommerfest.
> Update config.php 

- config.php
- workshopbash/index.php
- workshopdiv/index.php
- workshopgit/index.php
- workshoplatex/index.php
Added functionality to limit the maximum number of participants allowed to register. Set limit for Sommerfest to 260.
> Closes #21

- config.php
Fixed addition of duplicated code after resolving the conflict of my last PR.
> Fixed conflict merging error.

- config.php
Fixed a missing } in the function that checks the max number of participants.
> Added missing bracket

- config.php
- workshopgit/index.php
Changed times for the workshop events, date of Spieleabend and activated the Stadtrallye event.
> CHANGES WORKSHOP, STADTRALLYE, SPIELEABEND

- config.php
- index.php
As there are more events than 'Anfi' stuff we should change the Page title.
> Change naming scheme

- config.php
- spa0/index.php
- spa1/index.php
- workshoplatex2/index.php
Wurde mittels `php -S localhost:800` getestet
> Add Ersti events for SoSe 22

- workshopgit2/index.php
> fix short code

- config.php
> add new location to wanderung

- event_data.php
Please merge. Updated and enabled Spieleabend 2 on 02.05.
> Update Spieleabend 2 info

- .env
- config.php
- index.php
- utils.php
This will be useful when handling, e.g., credentials for email.
That means, this PR is useful for #86, #87, #88
> Add dotenv file support

- css/index.css
- css/style.css
- index.php
- utils.php
Closes #116 
- Add styling to buttons
- Add function to check if event time is in the past
- Visually distinguish past events on index page
> Minor changes to styling and visually distinguish past events

- participants.php
> Fix error in participants

- event_data.php
> Added dates in description

- event_data.php
Fix the missing comma introduced in #138
> Fix missing comma

- event_data.php
Please add my email to metas.php.
My handle is: jules
> Add spieleabend to event_data.php

- event_data.php
Ich habe noch keinen Mail handler, wäre cool, wenn jemand den für mich erstellen könnte (Daniel Busch im Uni Mail Format).
(Gerne dann auch metas im PR editieren)
> Add Mister X game

- .github/workflows/check_yml_integrity.yml
- check_yml_integrity.py
- events.yml
This PR will introduce a GitHub Action that will check on push (main branch) and PR the integrity of the events.yml file.
It addresses issue: #159
It checks
- the scheme of each event
- partially the data:
- valid timestamps
- unique filenames
-  unique keys (event identifier)
> GH Action to check yml integrity, fixes #159

- events.yml
we got one more pub for the pub crawl and therefore have 10 more spots
> Update KT limits to 70

- README.md
- check_yml_integrity.py
- event.php
- event_type.php
- i18n/de.json
- i18n/en.json
Adds a flag to denote if past members are welcome to attend events or not. Also adds the required logic and translation.
If and only if dinos are allowed there is now a note below the remaining open spots.
> Add flag for dinos (closes #171)

- events.yml
We reserved another pub and therefore have more space
> increase Limit of KT1 to 80

- README.md
- events.yml
second bbq is in may not april
> Termine sose25

- css/input.css
- head.php
Just a small fix for design consistency.
> Make text inputs look like pills

- README.md
- config.php
- css/style-fsi-fsk.css
- css/style-fsi-only.css
- css/style.css
- head.php
* moved important css vars to separate files
* add a new config value
* updated README
> add changeable themes
